name: build_debs
on:
  push:
    branches:
      - main
    tags:
      - "*"
jobs:
  build_debs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:bookworm-slim
      # volumes:
      #   - debs:/debs
    steps:
      - name: Install apkg
        run: uv tool install apkg
      - name: Install build deps
        run: |
          apt-get update && apt-get install -y --no-install-recommends \
            git \
            build-essential \
            libcmocka-dev \
            libpcre2-dev \
            pkg-config \
            cmake \
            debhelper \
            libssl-dev \
            libssh-dev \
            libpam0g-dev \
            libcurl4-openssl-dev \
            libsystemd-dev \
            valgrind \
            libsystemd-dev \
            systemd \
            graphviz

      - name: download sources
        run: |
          git config --global http.sslVerify false 
          cd ~
          git clone --depth=1 https://github.com/CESNET/libyang  
          git clone --depth=1 https://github.com/CESNET/libnetconf2.git  
          git clone --depth=1 https://github.com/sysrepo/sysrepo.git  
          git clone --depth=1 https://github.com/CESNET/Netopeer2.git 
          sed -i 's/-DCMAKE_BUILD_TYPE/-DENABLE_TLS=ON -DENABLE_SSH=ON -DCMAKE_BUILD_TYPE/g' \
             /root/libnetconf2/distro/pkg/deb/rules

      - name: build libyang
        run: |
          cd ~/libyang && uv tool run apkg build 
          apt install ~/libyang/pkg/pkgs/debian-12/libyang*/*.deb

      - name: build libnetconf2
        run: |
          cd ~/libnetconf2 && uv tool run apkg build 
          apt install ~/libnetconf2/pkg/pkgs/debian-12/libnetconf*/*.deb

      - name: build sysrepo
        run: |
          cd ~/sysrepo/ && uv tool run apkg build
          apt install ~/sysrepo/pkg/pkgs/debian-12/sysrepo*/*deb

      - name: build netopeer2
        run: |
          cd ~/Netopeer2 && uv tool run apkg build
          apt install ~/Netopeer2/pkg/pkgs/debian-12/netopeer2*/*deb

      - name: collect all debs
        run: mkdir -p /debs && cp ~/*/pkg/pkgs/debian-12/*/* /debs/

      - name: upload debs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: /debs/
          retention-days: 7

      - name: Publish release
        uses: ghalactic/github-release-from-tag@v5
        if: github.ref_type == 'tag'
        with:
          generateReleaseNotes: "true"
          assets: |
            - path: /debs/*
